version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: chat_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: chat_backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app:cached
      - backend_node_modules:/app/node_modules
    environment:
      PORT: 4000
      JWT_SECRET: your_jwt_secret
      JWT_REFRESH_SECRET: your_refresh_jwt_secret
      REFRESH_TOKEN_COOKIE_NAME: refreshToken
      DATABASE_TYPE: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: chatdb

volumes:
  postgres_data:
  backend_node_modules:
